In [5]:
import pandas as pd
import numpy as np
d=np.random.randint(0,100,(40*5)).reshape(40,5)
rno = [r for r in range(141,181)]
s=pd.DataFrame(data=d,columns=['jsf','flutter','co','iat','iat'],index=rno)
s

     jsf  flutter  co  iat  iat
141   47       49  44   80   60
142   95        8  51   19   77
143   98       45  41    5   40
144   28       95  67   60   52
145   89       94  69    4   36
146   43       46  99    6    7
147   97       53  84   88   77
148   49       56  43    2   50
149   85       56  65   17   33
150   94        1  31   40   90
151   33       30  27   43   75
152   70       46   8   31   11
153   90       89  49   22   40
154   45       15  65   50   16
155   81       75  76   41   14
156   43       57  39   85   15
157    0       23  60   98   32
158   78       27  87   25   84
159   98       23  64   20   94
160   16       75  42   50   97
161   41       63  59   90   43
162   26       18  32   64   13
163   15       22  76   85   74
164   81       35  89   49   29
165   37        1  76    7   50
166   69       49  43   76   19
167   73       17  23   15   28
168   55       90  69   77   25
169   74       49  36    4   16
170    2       21  48    6   73
171   78       90  27   17   88
172   97       70  78   28   55
173   31       62  84   87   61
174   30       32  84   57   97
175   57       18  23   14   29
176   63       50   3   46   32
177   82       57   2   96   22
178    2       29  83   13   78
179   48       83   6   76   12
180   25       92  36   32   83

In [1]:
c = ns["iat"][ns['iat']<35]
c

NameError: name 'ns' is not defined